# Server settings  
server:  
    port:8080  
    address:localhost  
  
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/springboot-ureport?useUnicode=true&characterEncoding=utf-8
     username: root
     password: 
     driver-class-name: com.mysql.jdbc.Driver        
        
# MyBatis  
mybatis:  
    typeAliasesPackage: indi.qiaolin.test.ureport.entity
    mapperLocations: classpath:/indi/qiaolin/**/mapper/*.xml  
  
# 分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql  
  
# 日志配置
logging:
  level:
    org.apache.ibatis: DEBUG
    
# ureport Mysql 存储
ureport.mysql.provider:
  prefix: qiaolin-
  disabled: false


# FTP 配置
ftp: 
 utils: 
   hostname: 192.168.56.1
   port: 21
   username: Administrator
   password: Liqiaolin
 factory: 
  hostname: 192.168.56.1
  port: 21 
  username: Administrator
  password: Liqiaolin
  client-timeout: 10000    
  encoding: utf8
#  retry-times: 
#  passive-mode: 
#  file-type: 
#  rename-uploaded: true
    
# ureport FTP 存储
ureport:
  ftp:
    provider:
      prefix: ftp-
      disabled: false
      basePath: ureport_file\
 
