# Server settings  
server:  
    port: 8080
  
spring:
  datasource:
     url: jdbc:mysql://192.168.153.131:3306/springboot-ureport?useUnicode=true&characterEncoding=utf-8
     username: root
     password: 123456
     driver-class-name: com.mysql.jdbc.Driver        
        
# MyBatis  
mybatis:  
    typeAliasesPackage: indi.qiaolin.test.ureport.entity
    mapperLocations: classpath:/indi/qiaolin/**/mapper/*.xml  
  
  
# 日志配置
logging:
  level:
    org.apache.ibatis: DEBUG
    
# ureport Mysql 存储
ureport.mysql.provider:
  prefix: qiaolin-
  disabled: false

# FTP 配置
ftp:
 factory:
#   不启用ftp
  enable: false
  hostname: 192.168.56.1
  port: 21
  username: Administrator
  password: Liqiaolin
  client-timeout: 10000
  encoding: utf8
#  retry-times: 
#  passive-mode: 
#  file-type: 
#  rename-uploaded: true
#  enable: true

# ureport FTP 存储
ureport:
  ftp:
    provider:
      prefix: ftp-
      disabled: false
      basePath: ureport_file\
 
